/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiTtsRouteImport } from './routes/api/tts'
import { Route as ApiTranscribeRouteImport } from './routes/api/transcribe'
import { Route as ApiGenerateInfograficoRouteImport } from './routes/api/generate-infografico'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as ApiCamaraTranscribeSegmentRouteImport } from './routes/api/camara-transcribe-segment'
import { Route as AuthenticatedRevisaoRouteImport } from './routes/_authenticated/revisao'
import { Route as AuthenticatedRegistroVivoRouteImport } from './routes/_authenticated/registro-vivo'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedLivrosRouteImport } from './routes/_authenticated/livros'
import { Route as AuthenticatedKlioRouteImport } from './routes/_authenticated/klio'
import { Route as AuthenticatedJardimRouteImport } from './routes/_authenticated/jardim'
import { Route as AuthenticatedIdentidadeRouteImport } from './routes/_authenticated/identidade'
import { Route as AuthenticatedHomeRouteImport } from './routes/_authenticated/home'
import { Route as AuthenticatedFacetasRouteImport } from './routes/_authenticated/facetas'
import { Route as AuthenticatedCamaraRouteImport } from './routes/_authenticated/camara'
import { Route as AuthenticatedAgendaRouteImport } from './routes/_authenticated/agenda'
import { Route as AuthenticatedChatIndexRouteImport } from './routes/_authenticated/chat.index'
import { Route as ApiPublicReadyRouteImport } from './routes/api/public/ready'
import { Route as ApiPublicHealthRouteImport } from './routes/api/public/health'
import { Route as AuthenticatedTrilhaThreadIdRouteImport } from './routes/_authenticated/trilha.$threadId'
import { Route as AuthenticatedChatThreadIdRouteImport } from './routes/_authenticated/chat.$threadId'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTtsRoute = ApiTtsRouteImport.update({
  id: '/api/tts',
  path: '/api/tts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiTranscribeRoute = ApiTranscribeRouteImport.update({
  id: '/api/transcribe',
  path: '/api/transcribe',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateInfograficoRoute = ApiGenerateInfograficoRouteImport.update({
  id: '/api/generate-infografico',
  path: '/api/generate-infografico',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCamaraTranscribeSegmentRoute =
  ApiCamaraTranscribeSegmentRouteImport.update({
    id: '/api/camara-transcribe-segment',
    path: '/api/camara-transcribe-segment',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedRevisaoRoute = AuthenticatedRevisaoRouteImport.update({
  id: '/revisao',
  path: '/revisao',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRegistroVivoRoute =
  AuthenticatedRegistroVivoRouteImport.update({
    id: '/registro-vivo',
    path: '/registro-vivo',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLivrosRoute = AuthenticatedLivrosRouteImport.update({
  id: '/livros',
  path: '/livros',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedKlioRoute = AuthenticatedKlioRouteImport.update({
  id: '/klio',
  path: '/klio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedJardimRoute = AuthenticatedJardimRouteImport.update({
  id: '/jardim',
  path: '/jardim',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIdentidadeRoute = AuthenticatedIdentidadeRouteImport.update({
  id: '/identidade',
  path: '/identidade',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHomeRoute = AuthenticatedHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFacetasRoute = AuthenticatedFacetasRouteImport.update({
  id: '/facetas',
  path: '/facetas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCamaraRoute = AuthenticatedCamaraRouteImport.update({
  id: '/camara',
  path: '/camara',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAgendaRoute = AuthenticatedAgendaRouteImport.update({
  id: '/agenda',
  path: '/agenda',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatIndexRoute = AuthenticatedChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicReadyRoute = ApiPublicReadyRouteImport.update({
  id: '/api/public/ready',
  path: '/api/public/ready',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicHealthRoute = ApiPublicHealthRouteImport.update({
  id: '/api/public/health',
  path: '/api/public/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedTrilhaThreadIdRoute =
  AuthenticatedTrilhaThreadIdRouteImport.update({
    id: '/trilha/$threadId',
    path: '/trilha/$threadId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChatThreadIdRoute =
  AuthenticatedChatThreadIdRouteImport.update({
    id: '/chat/$threadId',
    path: '/chat/$threadId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/camara': typeof AuthenticatedCamaraRoute
  '/facetas': typeof AuthenticatedFacetasRoute
  '/home': typeof AuthenticatedHomeRoute
  '/identidade': typeof AuthenticatedIdentidadeRoute
  '/jardim': typeof AuthenticatedJardimRoute
  '/klio': typeof AuthenticatedKlioRoute
  '/livros': typeof AuthenticatedLivrosRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/registro-vivo': typeof AuthenticatedRegistroVivoRoute
  '/revisao': typeof AuthenticatedRevisaoRoute
  '/api/camara-transcribe-segment': typeof ApiCamaraTranscribeSegmentRoute
  '/api/chat': typeof ApiChatRoute
  '/api/generate-infografico': typeof ApiGenerateInfograficoRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/tts': typeof ApiTtsRoute
  '/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
  '/trilha/$threadId': typeof AuthenticatedTrilhaThreadIdRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/ready': typeof ApiPublicReadyRoute
  '/chat/': typeof AuthenticatedChatIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/agenda': typeof AuthenticatedAgendaRoute
  '/camara': typeof AuthenticatedCamaraRoute
  '/facetas': typeof AuthenticatedFacetasRoute
  '/home': typeof AuthenticatedHomeRoute
  '/identidade': typeof AuthenticatedIdentidadeRoute
  '/jardim': typeof AuthenticatedJardimRoute
  '/klio': typeof AuthenticatedKlioRoute
  '/livros': typeof AuthenticatedLivrosRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/registro-vivo': typeof AuthenticatedRegistroVivoRoute
  '/revisao': typeof AuthenticatedRevisaoRoute
  '/api/camara-transcribe-segment': typeof ApiCamaraTranscribeSegmentRoute
  '/api/chat': typeof ApiChatRoute
  '/api/generate-infografico': typeof ApiGenerateInfograficoRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/tts': typeof ApiTtsRoute
  '/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
  '/trilha/$threadId': typeof AuthenticatedTrilhaThreadIdRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/ready': typeof ApiPublicReadyRoute
  '/chat': typeof AuthenticatedChatIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/agenda': typeof AuthenticatedAgendaRoute
  '/_authenticated/camara': typeof AuthenticatedCamaraRoute
  '/_authenticated/facetas': typeof AuthenticatedFacetasRoute
  '/_authenticated/home': typeof AuthenticatedHomeRoute
  '/_authenticated/identidade': typeof AuthenticatedIdentidadeRoute
  '/_authenticated/jardim': typeof AuthenticatedJardimRoute
  '/_authenticated/klio': typeof AuthenticatedKlioRoute
  '/_authenticated/livros': typeof AuthenticatedLivrosRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/registro-vivo': typeof AuthenticatedRegistroVivoRoute
  '/_authenticated/revisao': typeof AuthenticatedRevisaoRoute
  '/api/camara-transcribe-segment': typeof ApiCamaraTranscribeSegmentRoute
  '/api/chat': typeof ApiChatRoute
  '/api/generate-infografico': typeof ApiGenerateInfograficoRoute
  '/api/transcribe': typeof ApiTranscribeRoute
  '/api/tts': typeof ApiTtsRoute
  '/_authenticated/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
  '/_authenticated/trilha/$threadId': typeof AuthenticatedTrilhaThreadIdRoute
  '/api/public/health': typeof ApiPublicHealthRoute
  '/api/public/ready': typeof ApiPublicReadyRoute
  '/_authenticated/chat/': typeof AuthenticatedChatIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/agenda'
    | '/camara'
    | '/facetas'
    | '/home'
    | '/identidade'
    | '/jardim'
    | '/klio'
    | '/livros'
    | '/perfil'
    | '/registro-vivo'
    | '/revisao'
    | '/api/camara-transcribe-segment'
    | '/api/chat'
    | '/api/generate-infografico'
    | '/api/transcribe'
    | '/api/tts'
    | '/chat/$threadId'
    | '/trilha/$threadId'
    | '/api/public/health'
    | '/api/public/ready'
    | '/chat/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/agenda'
    | '/camara'
    | '/facetas'
    | '/home'
    | '/identidade'
    | '/jardim'
    | '/klio'
    | '/livros'
    | '/perfil'
    | '/registro-vivo'
    | '/revisao'
    | '/api/camara-transcribe-segment'
    | '/api/chat'
    | '/api/generate-infografico'
    | '/api/transcribe'
    | '/api/tts'
    | '/chat/$threadId'
    | '/trilha/$threadId'
    | '/api/public/health'
    | '/api/public/ready'
    | '/chat'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/agenda'
    | '/_authenticated/camara'
    | '/_authenticated/facetas'
    | '/_authenticated/home'
    | '/_authenticated/identidade'
    | '/_authenticated/jardim'
    | '/_authenticated/klio'
    | '/_authenticated/livros'
    | '/_authenticated/perfil'
    | '/_authenticated/registro-vivo'
    | '/_authenticated/revisao'
    | '/api/camara-transcribe-segment'
    | '/api/chat'
    | '/api/generate-infografico'
    | '/api/transcribe'
    | '/api/tts'
    | '/_authenticated/chat/$threadId'
    | '/_authenticated/trilha/$threadId'
    | '/api/public/health'
    | '/api/public/ready'
    | '/_authenticated/chat/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ApiCamaraTranscribeSegmentRoute: typeof ApiCamaraTranscribeSegmentRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiGenerateInfograficoRoute: typeof ApiGenerateInfograficoRoute
  ApiTranscribeRoute: typeof ApiTranscribeRoute
  ApiTtsRoute: typeof ApiTtsRoute
  ApiPublicHealthRoute: typeof ApiPublicHealthRoute
  ApiPublicReadyRoute: typeof ApiPublicReadyRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/tts': {
      id: '/api/tts'
      path: '/api/tts'
      fullPath: '/api/tts'
      preLoaderRoute: typeof ApiTtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transcribe': {
      id: '/api/transcribe'
      path: '/api/transcribe'
      fullPath: '/api/transcribe'
      preLoaderRoute: typeof ApiTranscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-infografico': {
      id: '/api/generate-infografico'
      path: '/api/generate-infografico'
      fullPath: '/api/generate-infografico'
      preLoaderRoute: typeof ApiGenerateInfograficoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/camara-transcribe-segment': {
      id: '/api/camara-transcribe-segment'
      path: '/api/camara-transcribe-segment'
      fullPath: '/api/camara-transcribe-segment'
      preLoaderRoute: typeof ApiCamaraTranscribeSegmentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/revisao': {
      id: '/_authenticated/revisao'
      path: '/revisao'
      fullPath: '/revisao'
      preLoaderRoute: typeof AuthenticatedRevisaoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/registro-vivo': {
      id: '/_authenticated/registro-vivo'
      path: '/registro-vivo'
      fullPath: '/registro-vivo'
      preLoaderRoute: typeof AuthenticatedRegistroVivoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/livros': {
      id: '/_authenticated/livros'
      path: '/livros'
      fullPath: '/livros'
      preLoaderRoute: typeof AuthenticatedLivrosRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/klio': {
      id: '/_authenticated/klio'
      path: '/klio'
      fullPath: '/klio'
      preLoaderRoute: typeof AuthenticatedKlioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jardim': {
      id: '/_authenticated/jardim'
      path: '/jardim'
      fullPath: '/jardim'
      preLoaderRoute: typeof AuthenticatedJardimRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/identidade': {
      id: '/_authenticated/identidade'
      path: '/identidade'
      fullPath: '/identidade'
      preLoaderRoute: typeof AuthenticatedIdentidadeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/home': {
      id: '/_authenticated/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AuthenticatedHomeRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/facetas': {
      id: '/_authenticated/facetas'
      path: '/facetas'
      fullPath: '/facetas'
      preLoaderRoute: typeof AuthenticatedFacetasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/camara': {
      id: '/_authenticated/camara'
      path: '/camara'
      fullPath: '/camara'
      preLoaderRoute: typeof AuthenticatedCamaraRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/agenda': {
      id: '/_authenticated/agenda'
      path: '/agenda'
      fullPath: '/agenda'
      preLoaderRoute: typeof AuthenticatedAgendaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat/': {
      id: '/_authenticated/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof AuthenticatedChatIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/ready': {
      id: '/api/public/ready'
      path: '/api/public/ready'
      fullPath: '/api/public/ready'
      preLoaderRoute: typeof ApiPublicReadyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/health': {
      id: '/api/public/health'
      path: '/api/public/health'
      fullPath: '/api/public/health'
      preLoaderRoute: typeof ApiPublicHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/trilha/$threadId': {
      id: '/_authenticated/trilha/$threadId'
      path: '/trilha/$threadId'
      fullPath: '/trilha/$threadId'
      preLoaderRoute: typeof AuthenticatedTrilhaThreadIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat/$threadId': {
      id: '/_authenticated/chat/$threadId'
      path: '/chat/$threadId'
      fullPath: '/chat/$threadId'
      preLoaderRoute: typeof AuthenticatedChatThreadIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAgendaRoute: typeof AuthenticatedAgendaRoute
  AuthenticatedCamaraRoute: typeof AuthenticatedCamaraRoute
  AuthenticatedFacetasRoute: typeof AuthenticatedFacetasRoute
  AuthenticatedHomeRoute: typeof AuthenticatedHomeRoute
  AuthenticatedIdentidadeRoute: typeof AuthenticatedIdentidadeRoute
  AuthenticatedJardimRoute: typeof AuthenticatedJardimRoute
  AuthenticatedKlioRoute: typeof AuthenticatedKlioRoute
  AuthenticatedLivrosRoute: typeof AuthenticatedLivrosRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedRegistroVivoRoute: typeof AuthenticatedRegistroVivoRoute
  AuthenticatedRevisaoRoute: typeof AuthenticatedRevisaoRoute
  AuthenticatedChatThreadIdRoute: typeof AuthenticatedChatThreadIdRoute
  AuthenticatedTrilhaThreadIdRoute: typeof AuthenticatedTrilhaThreadIdRoute
  AuthenticatedChatIndexRoute: typeof AuthenticatedChatIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAgendaRoute: AuthenticatedAgendaRoute,
  AuthenticatedCamaraRoute: AuthenticatedCamaraRoute,
  AuthenticatedFacetasRoute: AuthenticatedFacetasRoute,
  AuthenticatedHomeRoute: AuthenticatedHomeRoute,
  AuthenticatedIdentidadeRoute: AuthenticatedIdentidadeRoute,
  AuthenticatedJardimRoute: AuthenticatedJardimRoute,
  AuthenticatedKlioRoute: AuthenticatedKlioRoute,
  AuthenticatedLivrosRoute: AuthenticatedLivrosRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedRegistroVivoRoute: AuthenticatedRegistroVivoRoute,
  AuthenticatedRevisaoRoute: AuthenticatedRevisaoRoute,
  AuthenticatedChatThreadIdRoute: AuthenticatedChatThreadIdRoute,
  AuthenticatedTrilhaThreadIdRoute: AuthenticatedTrilhaThreadIdRoute,
  AuthenticatedChatIndexRoute: AuthenticatedChatIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ApiCamaraTranscribeSegmentRoute: ApiCamaraTranscribeSegmentRoute,
  ApiChatRoute: ApiChatRoute,
  ApiGenerateInfograficoRoute: ApiGenerateInfograficoRoute,
  ApiTranscribeRoute: ApiTranscribeRoute,
  ApiTtsRoute: ApiTtsRoute,
  ApiPublicHealthRoute: ApiPublicHealthRoute,
  ApiPublicReadyRoute: ApiPublicReadyRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
